name: CI Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files
      run: ls -R

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./src/LocalFriendzApi/LocalFriendzApi.csproj

    - name: Build
      run: dotnet build ./src/LocalFriendzApi/LocalFriendzApi.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test ./src/LocalFriendzApi.Test/LocalFriendzApi.IntegrationTests.csproj --configuration Release --no-build --verbosity normal
